# Generated by Django 5.0.2 on 2024-02-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='new_field',
        ),
    ]
